import type {NextPage} from 'next';
import type {GetStaticProps} from 'next';
import Head from 'next/head';

import type {
  GithubUser,
  Product,
  GithubRepository,
  GithubGist,
} from '../src/interfaces';
import {api} from '../src/utils';
import {Products} from '../src/assets/contents';

import {HomePage} from '../src/components/pages/HomePage';

type Props = {
  user: GithubUser;
  products: Product[];
  repositories: GithubRepository[];
  gists: GithubGist[];
};

const Home: NextPage<Props> = ({user, products, repositories, gists}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage
        user={user}
        products={products}
        repositories={repositories}
        gists={gists}
      />
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  // user
  const user = await api.fetchGithubUser();

  // repositories
  const repositories = await api.fetchGithubRepositories();
  const tenOrLessOriginalRepositories = repositories
    .filter(repo => !repo.fork)
    .slice(0, 10);

  // gists
  const gists: GithubGist[] = await api.fetchGithubGists();

  return {
    props: {
      user,
      products: Products,
      repositories: tenOrLessOriginalRepositories,
      gists,
    },
  };
};

export default Home;
